gui:
  scrollPastBottom: false
  expandFocusedSidePanel: true
  language: en
  mouseEvents: false
  showFileTree: false
  showBottomLine: false
  showRandomTip: false
  commandLogSize: 20
  skipRewordInEditorWarning: true
services:
  "<domain>": "gitlab:<domain>"
git:
  paging:
    colorArg: always
    useConfig: true
  log:
    showGraph: always
  autoFetch: false
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=oneline {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=oneline --"
  diffContextSize: 3
os:
  editCommand: "code"
  editCommandTemplate: "{{editor}} --goto -- {{filename}}:{{line}}"
  openCommand: "code -rg {{filename}}"
refresher:
  refreshInterval: 10
notARepository: skip
promptToReturnFromSubprocess: false
customCommands:
  - key: "U"
    command: "git reset --soft HEAD~1"
    description: "Undo last commit"
    context: "files"
  - key: "Q"
    command: "proxy-login.sh"
    description: "Execute proxy-login.sh"
    context: "global"
    stream: true
  - key: "e"
    command: "code '{{.SelectedFile.Name}}'"
    description: "edit file"
    context: "files"
  - key: "y"
    command: "pre-commit"
    description: "pre-commit"
    context: "files"
    subprocess: true
    stream: true
  - key: "y"
    command: "git pull --rebase"
    description: "pull (rebase)"
    context: "branch"
